package engine.entities;

import engine.graphics.Sprite;

/**
 * 
 * Holds preset data for various bullet/laser types.
 * Generated by BulletList class.
 * 
 * @author Daniel
 *
 */

public class BulletFrame extends CollidableFrame{
	
	// Bullet color
	private final int color;
	
	private final boolean spriteRotationBySpd;
	
	public BulletFrame(int type, int color, Sprite sprite, int hitboxType, int hitboxWidth, int hitboxLength, int hitboxOffset, boolean spriteAlign, float spriteRotation, boolean spriteRotationBySpd){
		super(type, sprite, hitboxType, hitboxWidth, hitboxLength, hitboxOffset, spriteAlign, spriteRotation);
		this.color = color;
		this.spriteRotationBySpd = spriteRotationBySpd;
	}
	
	public int getColor(){
		return color;
	}
	
	public boolean getSpriteRotationBySpd(){
		return spriteRotationBySpd;
	}
}
