package engine.entities;

import engine.graphics.Sprite;

/**
 * 
 * Holds preset data for various effect types.
 * Generated by EffectList class.
 * 
 * @author Daniel
 *
 */

public class EffectFrame extends EntityFrame{
	
	// Time until effect despawns
	private final int lifetime;
	
	public EffectFrame(int type, Sprite sprite, boolean spriteAlign, float spriteRotation, int lifetime){
		super(type, sprite, spriteAlign, spriteRotation);
		this.lifetime = lifetime;
	}
	
	public int getLifetime(){
		return lifetime;
	}
}
