package engine.entities;

import engine.graphics.Sprite;

/**
 * 
 * Holds preset data for various enemy types.
 * Generated by EnemyList class.
 * 
 * @author Daniel
 *
 */

public class EnemyFrame extends EntityFrame{
	
	private final int hitboxSize;
	
	public EnemyFrame(int type, Sprite sprite, int hitboxSize, boolean spriteAlign, float spriteRotation){
		super(type, sprite, spriteAlign, spriteRotation);
		this.hitboxSize = hitboxSize;
	}
	
	public int getHitboxSize(){
		return hitboxSize;
	}
}
