package engine.entities;

import engine.graphics.Sprite;

/**
 * 
 * Holds preset data for various enemy types.
 * Generated by EnemyList class.
 * 
 * @author Daniel
 *
 */

public class EnemyFrame extends CollidableFrame{
	
	public EnemyFrame(int type, Sprite sprite, int hitboxType, int hitboxWidth, int hitboxLength, int hitboxOffset, boolean spriteAlign, float spriteRotation){
		super(type, sprite, hitboxType, hitboxWidth, hitboxLength, hitboxOffset, spriteAlign, spriteRotation);
	}
}
